Ranking actores
TACS-1c2017-G1/TACS-1c2017-G1 pull request #24
Opened 2017-04-17 14:34 UTC by CiprianoAgustin

2017-04-17 20:43 UTC, ayelenMacarena requested changes
Lo rechazo mas que nada por lo del servicio. Ademas faltarían test de integración .

2017-04-17 20:43 UTC, ayelenMacarena commented on src/main/java/app/service/UserService.java
> +	SesionesService sesionesService = new SesionesService();
No hay que hacer el new, el Autowired se encarga de eso . Como estaba originalmente estaba bien.

2017-04-17 20:43 UTC, ayelenMacarena commented on src/main/java/app/service/UserService.java
> +			for (Actor actorFavoritoUsuario:usuario.getFavoriteActors()){
Esto no se puede hacer con stream y forEach? me parece que quedaría mejor.

2017-04-17 20:49 UTC, CiprianoAgustin commented on src/main/java/app/service/UserService.java
> +	SesionesService sesionesService = new SesionesService();
Corregido

2017-04-18 12:29 UTC, ayelenMacarena commented on src/main/java/app/service/UserService.java
> +			u.getFavoriteActors().stream().forEach(a ->{
No voy a ponerme en goma, pero u y a son poco expresivos :P

2017-04-18 12:29 UTC, merged